S_EIInd = 6;
S_IEInd = 5;

S_EIGridSz = S_EItest(2)-S_EItest(1);
S_IEGridSz = S_IEtest(2)-S_IEtest(1);

[a,b,c,d] = MeanFieldEst_BkGd_Indep_StepSize_ref_testL6(C_EE,C_EI,C_IE,C_II,...
                                            S_EE,...
                                            S_EItest(S_EIInd),...
                                            S_IEtest(S_IEInd)+0*S_IEGridSz...
                                            ,S_II,p_EEFail,...
                                            lambda_E,S_Elgn,rE_amb,S_amb,...
                                            lambda_I,S_Ilgn,rI_amb,...
                                            S_EL6,S_IL6,rE_L6,rI_L6,...
                                            tau_ampa_R,tau_ampa_D,tau_nmda_R,tau_nmda_D,tau_gaba_R,tau_gaba_D,tau_ref,...
                                            rhoE_ampa,rhoE_nmda,rhoI_ampa,rhoI_nmda,...
                                            gL_E,gL_I,Ve,Vi,...
                                            N_HC,n_E_HC,n_I_HC,'End',SampleNum,StopNum,h,SimuT);